# Generated by Django 5.2 on 2025-05-15 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="movie",
        ),
        migrations.RemoveField(
            model_name="review",
            name="user",
        ),
        migrations.DeleteModel(
            name="Movie",
        ),
        migrations.DeleteModel(
            name="Review",
        ),
    ]
