name: Build and Push Docker image to Amazon ECR

on:
  push:
    branches:
      - main  # Change if your default branch is different

jobs:
  deploy:
    name: Build and Push to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 143961844243.dkr.ecr.ap-south-1.amazonaws.com
          docker build -t django .
          docker tag django:latest 143961844243.dkr.ecr.ap-south-1.amazonaws.com/django:latest
          docker push 143961844243.dkr.ecr.ap-south-1.amazonaws.com/django:latest
